---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: anthill
subjects:
  - kind: ServiceAccount
    name: anthill
roleRef:
  kind: Role
  name: anthill
  apiGroup: rbac.authorization.k8s.io
