---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: anthill
rules:
  - apiGroups: [""]
    resources:
      - pods
      - services
      - endpoints
      - persistentvolumeclaims
      - events
      - configmaps
      - secrets
    verbs: ["create", "get", "list", "watch", "update", "delete"]
  - apiGroups: ["apps"]
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs: ["create", "get", "list", "watch", "update", "delete"]
  - apiGroups: ["monitoring.coreos.com"]
    resources:
      - servicemonitors
    verbs: ["get", "create"]
  - apiGroups: ["operator.gluster.org"]
    resources:
      - glusterclusters
      - glusternodes
    verbs: ["create", "get", "list", "watch", "update", "delete"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: anthill
subjects:
  - kind: ServiceAccount
    name: anthill
roleRef:
  kind: Role
  name: anthill
  apiGroup: rbac.authorization.k8s.io
